Repository tuono-labs/tuono-documentation, pull requests merged in 2025-03, with the labels that each got.

#40 feat(tutorial/api-fetching): improve text and snippet code
  src/routes/documentation/tutorial/api-fetching.mdx
Labels: enhancement

#43 docs(tutorial/components): improve text and snippet code
  src/routes/documentation/tutorial/components.mdx
Labels: enhancement

#44 feat(configuration): add `server.origin`
  src/routes/documentation/configuration.mdx
Labels: enhancement

#53 feat(tutorial/dynamic-routes): improve text and snippets
  src/routes/documentation/tutorial/dynamic-routes.mdx
Labels: enhancement

#29 feat: add page for environment variables
  src/components/Sidebar/sidebarElements.ts
  src/routes/documentation/environment-variables.mdx
Labels: enhancement, pending release

#59 feat: update `TuonoRouteProps` references
  src/routes/documentation/rendering/server-side-rendering.mdx
  src/routes/documentation/tutorial/api-fetching.mdx
  src/routes/documentation/tutorial/dynamic-routes.mdx
  src/routes/documentation/tutorial/seo.mdx
Labels: pending release
